## YAML Template.

excel_druck_prot: "C:\\Documents and Settings\\daniel_schmidt\\Work\\Bilfinger\\excel\df_protokoll.xls"
excel_wu_prot: "C:\Documents and Settings\daniel_schmidt\Work\Bilfinger\excel"